version: 0.1
env:
  variables:
    PATH: "$PATH:node-v6.11.5-linux-x64/bin"
  parameter-store:
    AWS_ACCESS_KEY_ID: "AccessKey"
    AWS_SECRET_ACCESS_KEY: "AccessKeySecret"
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - echo "Build info> "
      - uname -a
      - node --version
      - serverless deploy --stage cicd | tee deploy.out
    finally:
      - echo "Everything is done :-)" 
